### ISSUE TITLE
AuthorizationSuccessResponseHandler->AuthenticationSuccessHandler

### ISSUE THREAD

**Issue by rwinch** [jgrandja/oauth2-samples#18]
We should be able to convert the AuthorizationSuccessResponseHandler into an AuthenticationSuccessHandler rather than creating a new API. Yes OAuth is about Authorization, but before we do authorization, we validate the authenticity of the token which is authentication.

**Comment by jgrandja** [comment]
@rwinch I'm not sure if this makes sense. The `AuthenticationSuccessHandler` gets called right after a successful authentication. Therefore, we need an _authenticated_ `Authentication` before `AbstractAuthenticationProcessingFilter.successfulAuthentication` is called.

The 2 things that need to happen on the authorization code grant callback are:
1) Fetch the access token in exchange of the auth code
2) Call userInfo endpoint with access token to create the _authenticated_ `Authentication`

So I'm feeling we still need another API similar to the `AuthorizationSuccessResponseHandler` however it does seem confusing as you stated in #19....`onAuthorizationSuccess` followed by an `authenticate`. The naming should be changed here to avoid this confusion as authz is always after authn.

Any suggestions on another option for leveraging existing interface and avoiding having `AuthorizationSuccessResponseHandler`?

**Comment by rwinch** [comment]
Can't you perform this logic inside the AuthenticationProvider? This seems logical since the Authentication is not really resolved until the code is resolved and the user details are resolved.

**Comment by jgrandja** [comment]
Yes I did consider putting this logic in the AuthenticationProvider but we would still need a strategy for exchanging the auth code for the access token.

So I renamed AuthorizationSuccessResponseHandler to AuthorizationCodeGrantHandler. I think it makes sense to have the AuthorizationCodeGrantProcessingFilter delegate the auth code response callback to the AuthorizationCodeGrantHandler to handle the exchange of the auth code for the access token.

Then the AuthorizationCodeGrantProcessingFilter will create an OAuth2AuthenticationToken with the access token and the AuthenticationProvider will validate the authenticity of the token by calling the userInfo endpoint and ultimately validating the end-user authentication.

I applied these changes in this [commit](https://github.com/jgrandja/oauth2-samples/commit/3bb4f2b6418a2bf44b59a4a630136401d5046f6a).
Let me know if this makes sense.

**Comment by rwinch** [comment]
I don't think that it make sense for the `AuthenticationManager` to return successfully unless authentication has completed successfully (this is documented in the API docs of [AuthenticationManager](http://docs.spring.io/spring-security/site/docs/4.0.0.RELEASE/apidocs/org/springframework/security/authentication/AuthenticationManager.html#authenticate(org.springframework.security.core.Authentication)) and [AuthenticationProvider](http://docs.spring.io/spring-security/site/docs/4.0.0.RELEASE/apidocs/org/springframework/security/authentication/AuthenticationProvider.html#authenticate(org.springframework.security.core.Authentication))). Right now the `AuthenticationManager` might return successfully and the code could be invalid. This seems misleading to me.

Another issue is that `OAuth2AuthenticationProvider` currently tries to look up the roles for a user before the code has been validated. Most likely, users will want to map roles using an API call using access token which isn't available until later. 

I agree that you likely need another strategy, but I think it should be injected into the `OAuth2AuthenticationProvider`. Additionally, I don't think that the `HttpServletRequest` or `HttpServletResponse` need to be included in the arguments for this API. Likely it should just be a value object that contains Spring Security specific APIs necessary to get additional details.

**Comment by jgrandja** [comment]
@rwinch I'm confused regarding your comment:

> ...Right now the AuthenticationManager might return successfully and the code could be invalid

The last call in `attemptAuthentication` is `this.getAuthenticationManager().authenticate(authRequest)`
so if the `OAuth2AuthenticationProvider` is not able to fetch the useInfo, because of invalid token or user not found, then exception is thrown and caught by AbstractAuthenticationProcessingFilter.

Agreed that AuthenticationManager should only return on successful authentication. Am I missing something that you're seeing?

**Comment by jgrandja** [comment]
Regarding comment:

> Another issue is that OAuth2AuthenticationProvider currently tries to look up the roles for a user before the code has been validated.

The current sequence of calls in the provider is:

```
UserDetails userDetails = this.userInfoUserDetailsService.loadUserDetails(authenticationRequest);

Collection<? extends GrantedAuthority> authorities =
				this.authoritiesMapper.mapAuthorities(userDetails.getAuthorities());
```

The mapping of roles happens after the call to userInfo endpoint and the code was validated on previous call from `AuthorizationCodeGrantHandler` which exchanges the code for the access token.

I believe this is the correct sequence?

**Comment by rwinch** [comment]
Ok please disregard the the arguments above. I had a dated representation of the code in my head.

However, I'm still wondering what you have the logic outside of the `AuthenticationProvider`. From my perspective, it would be best to contain all the logic related to authenticating the user in the `AuthenticationProvider` this is the intention of this API.

**Comment by jgrandja** [comment]
> I agree that you likely need another strategy, but I think it should be injected into the OAuth2AuthenticationProvider.

I'm not sure if I agree with this one. I feel like the exchanging of the authorization code grant for an access token should be handled (indirectly) by the `AuthorizationCodeGrantProcessingFilter`.

The `AuthorizationCodeGrantProcessingFilter` is responsible for handling authorization code grant flows. It has 2 primary tasks:
1) it receives requests that contain an authorization code grant
2) it delegates the handling of the exchange of the code grant for an access token. The handling is delegated to the strategy `AuthorizationCodeGrantHandler`

The `AuthorizationCodeGrantProcessingFilter` then creates an `OAuth2AuthenticationToken` (includes the access token) and calls `AuthenticationManager` for authentication. The passed in `OAuth2AuthenticationToken` has `authenticated=false` because there is no `principal` set because of the constructor used. The `OAuth2AuthenticationProvider` will try to validate the authentication by delegating to `UserInfoUserDetailsService` to get the user info and return a `UserDetails` for the new `authenticated=true` `OAuth2AuthenticationToken` instance return by the provider.

**Comment by rwinch** [comment]
The request that is submitted to the container contains an Authorization Code Grant. How do you validate (authenticate) an Authorization Code Grant?

**Comment by jgrandja** [comment]
The client doesn't validate the authorization code. The Authorization Server will validate the authorization code from the token request and the requesting client to ensure that client is bound to that authorization code. If the token request is valid then it will return the access token. 

The returned access token will then be used to validate the end user authentication by calling the userIno endpoint.

**Comment by rwinch** [comment]
The client validates the authorization code by asking the server to provide
an access token. The authorization code is a temporary credential that
authenticates the user.

Think about it this way..would you consider the user authenticated if the
Authorization Server says the authorization code is invalid?

On Dec 12, 2016 14:45, "Joe Grandja" <notifications@github.com> wrote:

The client doesn't validate the authorization code. The Authorization
Server will validate the authorization code from the token request and the
requesting client to ensure that client is bound to that authorization
code. If the token request is valid then it will return the access token.

The returned access token will then be used to validate the end user
authentication by calling the userIno endpoint.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jgrandja/oauth2-samples/issues/18#issuecomment-266547343>,
or mute the thread

**Comment by jgrandja** [comment]
Agreed that authorization code is a temporary credential (for the client) however it doesn't necessarily authenticate the user. An access token with scopes assigned openid or non-standard user, email, profile scopes will allow access to the userInfo endpoint which ultimately validates the user authentication.

The user would not be authenticated if the authorization code is invalid because the AuthenticationManager would never get called.
